---
settings:
  name: Azure Blob storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de almacenamiento de Azure Blob
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Ver tus cuentas de almacenamiento de Azure Blob
      url: "/task-view-azure-blob-storage.html"
  - title: Gestionar cuentas de almacenamiento de Azure Blob
    entries:
    - title: Añada nuevas cuentas de almacenamiento
      url: "/task-add-blob-storage.html"
    - title: Cambie la configuración de las cuentas de almacenamiento
      url: "/task-change-blob-storage-settings.html"
    - title: Use los servicios de datos de NetApp con el almacenamiento de Azure Blob
      url: "/task-blob-enable-data-services.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
